# This config file for Travis CI utilizes ros-industrial/industrial_ci package.		
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst		
sudo: required 		
dist: trusty 		
services:		
  - docker		
language: generic 		
compiler:		
  - gcc		
notifications:		
  email:
    on_success: never
    on_failue: never
  slack: ouxt-polaris-2018:NclavkPPXCVkysAoOTr47aUg
env:		
  global:		
    - CATKIN_PARALLEL_TEST_JOBS=-p1
    - ROS_PARALLEL_TEST_JOBS=-j`nproc`
    - UPSTREAM_WORKSPACE=file
  matrix:		
    - ROS_DISTRO=kinetic ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO=melodic ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
install:	
  - apt install wget
  - wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
  - tar xvf cmake-3.15.2.tar.gz
  - cd cmake-3.15.2 && ./bootstrap && make && make install
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config		
script:		
- source .ci_config/travis.sh 